# Gitlab CI Docker Image
image: node:8.10.0

# Build - Build necessary JS files
# Test - Run tests
# Deploy - Deploy applicatino to S3/ElasticBeanstalk
stages:
- test
- build
- deploy

# Configuration
variables:
  AWS_DEFAULT_REGION: "us-east-2"
  EB_APP_NAME: "backend" # ELasticBeanstalk Application Name
  EB_APP_ENV: "BookingApp-dev" # ElasticBeanstalk Application ENvironment
  S3_BUCKET: "BookingApp" # S3 bucket for ElasticBeanstalk
  S3_KEY: "backend" # S3 folder to upload build app

# Job: Test
# Run tests against our application
# If this fails, we do not deploy
test:
  stage: test
  script:
  - yarn test

# Job: Build
# Installs npm packages, transpiles ES6 -> ES5
# Passes node_modules/, dist/, onto next steps using artifacts
build:
  stage: build
  script:
  - yarn
  - yarn build
  artifacts:
    paths:
    - node_modules/
    - dist/

# Job: Deploy
# Zips the contents of our built application, uploads to S3
# Configures a new EB version and switches to that version
deploy:
  stage: deploy
  script:
  - ./bin/deploy.sh
  only:
  - master